# Generated by Django 6.0.6 on 2026-06-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_category',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='shop.category'),
        ),
    ]
