# Generated by Django 6.0.6 on 2026-06-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_profile_favorite_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_categories',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
